### ISSUE TITLE
User status and profile picture functionality

### ISSUE THREAD

**Issue by HamsikaG** [HarshithaGandamalla/WhatsUpClone#11]

**Comment by HarshithaGandamalla** [comment]
![screenshot 28](https://user-images.githubusercontent.com/22549994/31846337-47fbb6ca-b5d8-11e7-8029-84a9ca88bdd3.png)
Please add profile picture functionality.
-Should be similar to picture below on clicking the profile option on settings drop down.
![screenshot 29](https://user-images.githubusercontent.com/22549994/31846349-820ca446-b5d8-11e7-9f20-019cba24438a.png)
